apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #TODO: make more generic
    path: "/Users/rjmccabe/repos/k8s_demo/jenkins_storage"
    # path: "/mnt/data"
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins
#   #annotations:
#    #pv.beta.kubernetes.io/gid: "1000"
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#   - ReadWriteOnce
#   azureFile:
#     secretName: storage-connection
#     secretNamespace: jenkins
#     shareName: {{ .Values.jenkins.azurefileshare }}
#     readOnly: false
#   claimRef:
#     name: jenkins-pvc
#     kind: PersistenVolumeClaim
#     namespace: jenkins
#   persistentVolumeReclaimPolicy: Retain
